## Below properties should be updated as per your authorization server configuration
server:
 port: 8081
jwt:
 issuerUrl: https://<my-dev-account>.oktapreview.com/oauth2/default
 aud: api://default
 clientId: <my-client-id>
serverResourceId: api://default
